{"name": "Параметризованная проверка невозможности авторизации курьера без передачи логина или пароля", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидаемый код: 400, полученный код: 504, ожидаемый текст содержит:         \"Недостаточно данных для входа\", полученный текст: Service unavailable\nassert (400 == 504)\n +  where 504 = <Response [504]>.status_code", "trace": "self = <tests.test_courier_login.TestCourierLogin object at 0x000002B8FE00A450>, generate_courier_data = {'firstName': 'Tara', 'login': 'barkeralexandra'}\nmissing_argument = 'password'\n\n    @allure.title('Параметризованная проверка невозможности авторизации курьера без передачи логина или пароля')\n    @allure.description('Создаем курьера, пытаемся авторизоваться без логина или пароля,проверяем что \\\n            код ответа: 400, текст ответа: \"Недостаточно данных для входа\"')\n    @pytest.mark.parametrize('missing_argument', (('login'), ('password')))\n    def test_login_courier_without_login_or_password_fail(self, generate_courier_data, missing_argument):\n        requests.post(f'{Data.main_url}/api/v1/courier', data=generate_courier_data)\n        del generate_courier_data[missing_argument]\n        response = requests.post(f'{Data.main_url}/api/v1/courier/login', data=generate_courier_data)\n>       assert 400 == response.status_code and 'Недостаточно данных для входа' in response.text, \\\n        f'Ожидаемый код: 400, полученный код: {response.status_code}, ожидаемый текст содержит: \\\n        \"Недостаточно данных для входа\", полученный текст: {response.text}'\nE       AssertionError: Ожидаемый код: 400, полученный код: 504, ожидаемый текст содержит:         \"Недостаточно данных для входа\", полученный текст: Service unavailable\nE       assert (400 == 504)\nE        +  where 504 = <Response [504]>.status_code\n\ntests\\test_courier_login.py:29: AssertionError"}, "description": "Создаем курьера, пытаемся авторизоваться без логина или пароля,проверяем что             код ответа: 400, текст ответа: \"Недостаточно данных для входа\"", "parameters": [{"name": "missing_argument", "value": "'password'"}], "start": 1710001600052, "stop": 1710001660579, "uuid": "3c2a29b8-2212-4341-8978-84ec3ab56913", "historyId": "c5edcbea6f43bf148a8fcd0a0469817a", "testCaseId": "ec127e2a3849c2081030809b15eab71f", "fullName": "tests.test_courier_login.TestCourierLogin#test_login_courier_without_login_or_password_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-1VNC7DB"}, {"name": "thread", "value": "34604-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}